In [1]:
#Import NumPy in Python
import numpy as np
#The code above imports the numpy library in our program as an alias np.

In [3]:
#Create Array Using Python List
#We can create a NumPy array using a Python List. For example,
import numpy as np

# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)
print(list1)

#Here, we have created an array by passing list1 as an argument to the np.array() function.

[2 4 6 8]
[2, 4, 6, 8]


In [4]:
#Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.
#For example,
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)
#same output as the previous

[2 4 6 8]


Unlike lists, arrays can only store data of a similar type.

In [6]:
#Create an Array Using np.zeros()
#The np.zeros() function allows us to create an array filled with all zeros.
# create an array with 4 elements filled with zeros
array1 = np.ones(4)

print(array1)

[1. 1. 1. 1.]


In [7]:
array1 = np.zeros(4)

print(array1)

[0. 0. 0. 0.]


Create an Array With np.arange()

In [10]:
#The np.arange() function returns an array with values within a specified interval.
# create an array with values from 0 to 4
array1 = np.arange(5)

print("Using np.arange(5):", array1)

# create an array with values from 1 to 8 with a step of 2
array2 = np.arange(1, 15, 4)

print("Using np.arange(1, 9, 2):",array2)

Using np.arange(5): [0 1 2 3 4]
Using np.arange(1, 9, 2): [ 1  5  9 13]


In [11]:
#Create an Array With np.random.rand()
#The np.random.rand() function is used to create an array of random numbers.

#an example to create an array of 5 random numbers
# generate an array of 5 random numbers
array1 = np.random.rand(5)

print(array1)

[0.53145342 0.83217606 0.91037081 0.39457624 0.07150087]


In [15]:
#Create an Empty NumPy Array
#To create an empty NumPy array, we use the np.empty() function.
# create an empty array of length 4
array1 = np.empty(4)

print(array1)

[0. 0. 0. 0.]


If we look into the output of the code, we can see the empty array is actually not empty, it has some values in it.

It is because although we are creating an empty array, NumPy will try to add some value to it. The values stored in the array are arbitrary and have no significance.

In [ ]:
#N-D Array Creation From List of Lists
#To create an N-dimensional NumPy array from a Python List, we can use the np.array() function and pass the list as an argument.

In [16]:
#Create a 2-D NumPy Array
#create a 2D NumPy array with 2 rows and 4 columns using lists.
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
#Create a 3-D NumPy Array
#create a 3-D NumPy array consisting of two "slices" where each slice has 3 rows and 4 columns.
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


Here, we created a 3D list [list of lists of lists] and passed it to the np.array() function. This creates the 3-D array named array1.

In the 3D list,

The outermost list contains two elements, which are lists representing the two "slices" of the array. Each slice is a 2-D array with 3 rows and 4 columns.
The innermost lists represent the individual rows of the 2-D arrays.
In the context of an N-D array, a slice is like a subset of the array that we can take out by selecting a specific range of rows, columns.

Creating N-d Arrays From Scratch. We saw how to create N-d NumPy arrays from Python lists. Now we'll see how we can create them from scratch.



In [ ]:
#To create multidimensional arrays from scratch we use functions such as

#np.zeros()
#np.arange()
#np.random.rand()

In [18]:
#Create N-D Arrays using np.zeros()
#The np.zeros() function allows us to create N-D arrays filled with all zeros.
# create 2D array with 2 rows and 3 columns filled with zeros
array1 = np.zeros((2, 3))

print("2-D Array: ")
print(array1)

# create 3D array with dimensions 2x3x4 filled with zeros
array2 = np.zeros((2, 3, 4))

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0. 0. 0.]
 [0. 0. 0.]]

3-D Array: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


np.zeros((2, 3)) - returns a zero filled 2-D array with 2 rows and 3 columns


np.zeros((2, 3, 4)) - returns a zero filled 3-D array with 2 slices, each slice having 3 rows and 4 columns.

In [19]:
#Create N-D Array with a Specified Value
 #to create a 2-D array with the value 5
 # Create a 2-D array with elements initialized to 5
numpy_array = np.full((2, 2), 5)

print("Array:", numpy_array)

Array: [[5 5]
 [5 5]]


In [20]:
#Creating Arrays With np.random.rand()
#The np.random.rand() function is used to create an array of random numbers.
# create a 2D array of 2 rows and 2 columns of random numbers
array1 = np.random.rand(2, 2)

print("2-D Array: ")
print(array1)

# create a 3D array of shape (2, 2, 2) of random numbers
array2 = np.random.rand(2, 2, 2)

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[0.38489836 0.60190278]
 [0.17901749 0.94319813]]

3-D Array: 
[[[0.70885878 0.24242599]
  [0.55088669 0.15444739]]

 [[0.2158448  0.67920974]
  [0.22823743 0.39765482]]]


np.random.rand(2, 2) - creates a 2D array of 2 rows and 2 columns of random numbers.

np.random.rand(2, 2, 2) - creates a 3D array with 2 slices, each slice having 2 rows and 2 columns of random numbers.

In [21]:
#Check Data Type of a NumPy Array
#To check the data type of a NumPy array, we can use the dtype attribute.
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)

int64


Since array1 is an array of integers, the data type of array1 is inferred as int64 by default.

In [22]:
#Check Data Type of NumPy Array
# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)  # prints int64

# check the data type of float_array
print(float_array.dtype)  # prints float64

# check the data type of complex_array
print(complex_array.dtype)  # prints complex128

int64
float64
complex128


int_array - contains four integer elements whose default data type is int64


float_array - contains three floating-point numbers whose default data type is float64


complex_array - contains three complex numbers whose default data type is complex128

In [23]:
#Creating NumPy Arrays With a Defined Data Type
#In NumPy, we can create an array with a defined data type by passing the dtype parameter while calling the np.array() function.
# create an array of 32-bit integers
array1 = np.array([1, 3, 7], dtype='int32')

print(array1, array1.dtype)

[1 3 7] int32


Here, inside np.array(), we have passed an array [1, 3, 7] and set the dtype parameter to int32.

Since we have set the data type of the array to int32, each element of the array is represented as a 32-bit integer.

In [24]:
#NumPy Type Conversion
#In NumPy, we can convert the data type of an array using the astype() method.
# create an array of integers
int_array = np.array([1, 3, 5, 7])

# convert data type of int_array to float
float_array = int_array.astype('float')

# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[1 3 5 7] int64
[1. 3. 5. 7.] float64


Here, int_array.astype('float') converts the data type of int_array from int64 to float64 using astype().

In [25]:
#To access the Numpy attributes, we use the . notation
array1.ndim
#This returns the number of dimensions in array1.

1

In [26]:
#The ndim attribute returns the number of dimensions in the numpy array.
# create a 2-D array
array1 = np.array([[2, 4, 6],
                  [1, 3, 5]])

# check the dimension of array1
print(array1.ndim)


2


In this example, array1.ndim returns the number of dimensions present in array1. As array1 is a 2D array, we got 2 as an output.

In [27]:
#NumPy Array size Attribute
#The size attribute returns the total number of elements in the given array.
array1 = np.array([[1, 2, 3],
                 [6, 7, 8]])

# return total number of elements in array1
print(array1.size)

#Since these are a total of 6 elements in array1, the size attribute returns 6.

6


In [28]:
#NumPy Array shape Attribute
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)

(2, 3)


In [30]:
#NumPy Array itemsize Attribute
#In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13, 18, 29, 22])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)  # prints 8
print(array2.itemsize)  # prints 4

8
4


array1 is an array containing 64-bit integers by default, which uses 8
bytes of memory per element. So, itemsize returns 8 as the size of each element.


array2 is an array of 32-bit integers, so each element in this array uses only 4 bytes of memory. So, itemsize returns 4 as the size of each element.


In [31]:
#NumPy Array data Attribute
#In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

 #The data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                  [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7bfc8b2d8280>
Data of array2 is:  <memory at 0x7bfcc0276330>


In [ ]:
#Most Commonly Used I/O Functions-
#save()	saves an array to a binary file in the NumPy .npy format.
#load()	loads data from a binary file in the NumPy .npy format
#savetxt()	saves an array to a text file in a specific format
#loadtxt()


In [34]:
#NumPy save() Function
#In NumPy, the save() function is used to save an array to a binary file in the NumPy .npy format.
# create a NumPy array
array1 = np.array([[1, 3, 5],
                   [7, 9, 11]])

# save the array to a file
np.save('file1.npy', array1)


In NumPy, the save() function is used to save an array to a binary file in the NumPy .npy format.

we saved the NumPy array named array1 to the binary file named file1.npy in our current directory.

In [35]:
# load the saved NumPy array
loaded_array = np.load('file1.npy')

# display the loaded array
print(loaded_array)

[[ 1  3  5]
 [ 7  9 11]]


Here, we have used the load() function to read a binary file named file1.npy.

This is the same file we created and saved using save() function in the last example.

In [37]:
# create a NumPy array
array2 = np.array([[1, 3, 5],
                   [7, 9, 11]])

# save the array to a file
np.savetxt('file2.txt', array2)

The code above will save the NumPy array array2 to the text file named file2.txt in our current directory.

In [38]:
#NumPy loadtxt() Function
#We use the loadtxt() function to load the saved txt file.

#To load the file2.txt file that we saved earlier.
# load the saved NumPy array
loaded_array = np.loadtxt('file2.txt')

# display the loaded array
print(loaded_array)

#The values in the loaded array have dots . because loadtxt() reads the values as floating point numbers by default.

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


Here, we have used the loadtxt() function to load the text file named file2.txt that was previously created and saved using the savetxt() function.