In [2]:
#NumPy Arithmetic Array Operations
#perform element-wise addition between two NumPy arrays.
import numpy as np
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print("Using the + operator:",result1)

# using the add() function
result2 = np.add(first_array, second_array)
print("Using the add() function:",result2)

Using the + operator: [ 3  7 11 15]
Using the add() function: [ 3  7 11 15]


In [3]:
#NumPy Array Element-Wise Subtraction
#In NumPy, we can either use the - operator or the subtract() function to perform element-wise subtraction between two NumPy arrays.
first_array = np.array([3, 9, 27, 81])
second_array = np.array([2, 4, 8, 16])

# using the - operator
result1 = first_array - second_array
print("Using the - operator:",result1)

# using the subtract() function
result2 = np.subtract(first_array, second_array)
print("Using the subtract() function:",result2)

Using the - operator: [ 1  5 19 65]
Using the subtract() function: [ 1  5 19 65]


In [4]:
#NumPy Array Element-Wise Multiplication
first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the * operator
result1 = first_array * second_array
print("Using the * operator:",result1)

# using the multiply() function
result2 = np.multiply(first_array, second_array)
print("Using the multiply() function:",result2)

Using the * operator: [ 2 12 30 56]
Using the multiply() function: [ 2 12 30 56]


In [5]:
first_array = np.array([1, 2, 3])
second_array = np.array([4, 5, 6])

# using the / operator
result1 = first_array / second_array
print("Using the / operator:",result1)

# using the divide() function
result2 = np.divide(first_array, second_array)
print("Using the divide() function:",result2)

Using the / operator: [0.25 0.4  0.5 ]
Using the divide() function: [0.25 0.4  0.5 ]


In [6]:
#NumPy Array Creation Functions
# create an array using np.array()
array1 = np.array([1, 3, 5])
print("np.array():\n", array1)

# create an array filled with zeros using np.zeros()
array2 = np.zeros((3, 3))
print("\nnp.zeros():\n", array2)

# create an array filled with ones using np.ones()
array3 = np.ones((2, 4))
print("\nnp.ones():\n", array3)


#np.array() - creates an array from a Python List
#np.zeros() - creates an array filled with zeros of the specified shape
#np.ones() - creates an array filled with ones of the specified shape

np.array():
 [1 3 5]

np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#NumPy Array Manipulation Functions
#NumPy array manipulation functions allow us to modify or rearrange NumPy arrays.
# create a 1D array
array1 = np.array([1, 3, 5, 7, 9, 11])

# reshape the 1D array into a 2D array
array2 = np.reshape(array1, (2, 3))

# transpose the 2D array
array3 = np.transpose(array2)

print("Original array:\n", array1)
print("\nReshaped array:\n", array2)
print("\nTransposed array:\n", array3)


#np.reshape(array1, (2, 3)) - reshapes array1 into 2D array with shape (2,3)
#np.transpose(array2) - transposes 2D array array2

Original array:
 [ 1  3  5  7  9 11]

Reshaped array:
 [[ 1  3  5]
 [ 7  9 11]]

Transposed array:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]


In [8]:
#NumPy Array Statistical Functions
#statistical functions are useful to find basic statistical concepts like mean, median, variance, etc.
#It is also used to find the maximum or the minimum element in an array.
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)
print("Mean:",mean_marks)

# compute the median of marks
median_marks = np.median(marks)
print("Median:",median_marks)

# find the minimum and maximum marks
min_marks = np.min(marks)
print("Minimum marks:", min_marks)

max_marks = np.max(marks)
print("Maximum marks:", max_marks)

Mean: 77.2
Median: 78.0
Minimum marks: 66
Maximum marks: 85


In [11]:
#NumPy Array Input/Output Functions
# create an array
array1 = np.array([[1, 3, 5], [2, 4, 6]])

# save the array to a text file
np.savetxt('data.txt', array1)

# load the data from the text file
loaded_data = np.loadtxt('data.txt')

# print the loaded data
print(loaded_data)

#In this example, we first created the 2D array named array1 and then saved it to a text file using the np.savetxt() function.

#We then loaded the saved data using the np.loadtxt() function.

[[1. 3. 5.]
 [2. 4. 6.]]


In [12]:
#NumPy Comparison Operators
array1 = np.array([1, 2, 3])
array2 = np.array([3, 2, 1])

# less than operator
result1 = array1 < array2
print("array1 < array2:",result1)    # Output: [ True False False]

# greater than operator
result2 = array1 > array2
print("array1 > array2:",result2)    # Output: [False False  True]

# equal to operator
result3 = array1 == array2
print("array1 == array2:",result3)    # Output: [False  True False]

#the output of the comparison operators is also an array, where each element is either True or False based on the array element's comparison.

array1 < array2: [ True False False]
array1 > array2: [False False  True]
array1 == array2: [False  True False]


In [13]:
array1 = np.array([9, 12, 21])
array2 = np.array([21, 12, 9])

# use of less()
result = np.less(array1, array2)
print("Using less():",result)    # Output: [ True False False]

# use of less_equal()
result = np.less_equal(array1, array2)
print("Using less_equal():",result)     # Output: [ True  True False]

# use of greater()
result = np.greater(array1, array2)
print("Using greater():",result)    # Output: [False False  True]

# use of greater_equal()
result = np.greater_equal(array1, array2)
print("Using greater_equal():",result)    # Output: [False  True  True]

# use of equal()
result = np.equal(array1, array2)
print("Using equal():",result)    # Output: [False  True False]

# use of not_equal()
result = np.not_equal(array1, array2)
print("Using not_equal():",result)    # Output: [ True False  True]

Using less(): [ True False False]
Using less_equal(): [ True  True False]
Using greater(): [False False  True]
Using greater_equal(): [False  True  True]
Using equal(): [False  True False]
Using not_equal(): [ True False  True]


In [14]:
x1 = np.array([True, False, True])
x2 = np.array([False, False, True])

# Logical AND
print(np.logical_and(x1, x2)) # Output: [False False  True]

# Logical OR
print(np.logical_or(x1, x2)) # Output: [ True False  True]

# Logical NOT
print(np.logical_not(x1)) # Output: [False  True False]

#Here, we have performed logical operations on two arrays, x1 and x2, containing boolean values.

#It demonstrates the logical AND, OR, and NOT operations using np.logical_and(), np.logical_or(), and np.logical_not() respectively.

[False False  True]
[ True False  True]
[False  True False]


In [15]:
#Compute Median for Even Number of Elements
# create a 1D array with 6 elements
array1 = np.array([1, 2, 3, 4, 5, 7])

# calculate the median
median = np.median(array1)
print(median)

3.5


In [16]:
#Compute Mean Using NumPy
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

77.2


In [17]:
#Compute the Standard Deviation of a 2D array.
# create a 2D array
array1 = np.array([[2, 5, 9],
                 [3, 8, 11],
                 [4, 6, 7]])

# compute standard deviation along horizontal axis
result1 = np.std(array1, axis=1)
print("Standard deviation along horizontal axis:", result1)

# compute standard deviation along vertical axis
result2 = np.std(array1, axis=0)
print("Standard deviation  along vertical axis:", result2)

# compute standard deviation of entire array
result3 = np.std(array1)
print("Standard deviation of entire array:", result3)


#Here, we have created a 2D array named array1.

#We then computed the standard deviation along horizontal and vertical axis individually and then computed the standard deviation of the entire array.

Standard deviation along horizontal axis: [2.86744176 3.29983165 1.24721913]
Standard deviation  along vertical axis: [0.81649658 1.24721913 1.63299316]
Standard deviation of entire array: 2.7666443551086073


In a 2D array, standard deviation can be calculated either along the horizontal or the vertical axis individually, or across the entire array.

Similar to mean and median, when computing the standard deviation of a 2D array, we use the axis parameter inside np.std() to specify the axis along which to compute the standard deviation.

In [19]:
#NumPy String add() Function
array1 = np.array(['iPhone: ', 'price: '])
array2 = np.array(['15', '$900'])

# perform element-wise array string concatenation
result = np.char.add(array1, array2)

print(result)


#In this example, we have defined two NumPy arrays: array1 and array2, with string elements 'iphone: ' and 'price: ' and '15' and '$900' respectively.

#We then used np.char.add(array1, array2) to concatenate the elements of array1 and array2 element-wise.

#Finally, we have stored the concatenated string in result, which in our case are 'iPhone: 15' and 'price: $900'.

['iPhone: 15' 'price: $900']


In [20]:
#NumPy String multiply() Function
# define array with three string elements
array1 = np.array(['A', 'B', 'C'])

#  repeat each element in array1 two times
result = np.char.multiply(array1, 2)

print(result)

['AA' 'BB' 'CC']


In [21]:
#NumPy String capitalize() Function
# define an array with three string elements
array1 = np.array(['eric', 'paul', 'sean'])

# capitalize the first letter of each string in array1
result = np.char.capitalize(array1)

print(result)

['Eric' 'Paul' 'Sean']


In [22]:
#NumPy String upper() and lower() Function
#NumPy provides two string functions for converting the case of a string: np.char.upper() and np.char.lower().
array1 = np.array(['nEpalI', 'AmeriCAN', 'CaNadIan'])

# convert all string elements to uppercase
result1 = np.char.upper(array1)

# convert all string elements to lowercase
result2 = np.char.lower(array1)

print("To Uppercase: ",result1)
print("To Lowercase: ",result2)

To Uppercase:  ['NEPALI' 'AMERICAN' 'CANADIAN']
To Lowercase:  ['nepali' 'american' 'canadian']
