In [ ]:
#Numpy Array Indexing
#Access Array Elements Using Index
import numpy as np

array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])    # prints 1
print(array1[2])    # prints 5
print(array1[4])    # prints 9

1
5
9


Since the last element of array1 is at index 4, if we try to access the element beyond that, say index 5, we will get an index error:

In [ ]:
#Modify Array Elements Using Index
#We can use indices to change the value of an element in a NumPy array
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10])

# change the value of the first element
numbers[0] = 12
print("After modifying first element:",numbers)    # prints [12 4 6 8 10]

# change the value of the third element
numbers[2] = 14
print("After modifying third element:",numbers)    # prints [12 4 14 8 10]

After modifying first element: [12  4  6  8 10]
After modifying third element: [12  4 14  8 10]


In [ ]:
#NumPy Negative Array Indexing
#NumPy allows negative indexing for its array. The index of -1 refers to the last item, -2 to the second last item and so on.
# create a numpy array
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])    # prints 9

# access the second-to-last element
print(numbers[-2])    # prints 7

9
7


In [ ]:
#2-D NumPy Array Indexing
#Array indexing in NumPy allows us to access and manipulate elements in a 2-D array.

#To access an element of array1, we need to specify the row index and column index of the element. Suppose we have following 2-D array,
array1 = np.array([[1, 3, 5],
                     [7, 9, 2],
                     [4, 6, 8]])
array1[2, 1] # returns 6

6

Since we know indexing starts from 0. So to access the element in the third row and second column, we need to use index 2 for the third row and index 1 for the second column respectively.

In [ ]:
#2-D NumPy Array Indexing
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                  [9, 11, 13, 15],
                  [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [ ]:
#Access Row or Column of 2D Array Using Indexing
#we can access specific rows or columns of a 2-D array using array indexing.
# create a 2D array
array1 = np.array([[1, 3, 5],
             [7, 9, 2],
             [4, 6, 8]])

# access the second row of the array
second_row = array1[1, :]
print("Second Row:", second_row)  # Output: [7 9 2]

# access the third column of the array
third_col = array1[:, 2]
print("Third Column:", third_col)  # Output: [5 2 8]

Second Row: [7 9 2]
Third Column: [5 2 8]


array1[1, :] - access the second row of array1


array1[:, 2] - access the third column of array1


In [ ]:
#3-D NumPy Array Indexing
#We learned how to access elements in a 2D array. We can also access elements in higher dimensional arrays.

#To access an element of a 3D array, we use three indices separated by commas.

#The first index refers to the slice
#The second index refers to the row
#The third index refers to the column.
#In 3D arrays, slice is a 2D array that is obtained by taking a subset of the elements in one of the dimensions.
import numpy as np
# create a 3D array with shape (2, 3, 4)
array1 = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],

                    [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]])

# access a specific element of the array
element = array1[1, 2, 1]

# print the value of the element
print(element)

22


Here, we created a 3D array called array1 with shape (2, 3, 4). This array contains 2 2D arrays, each with 3 rows and 4 columns.

Then, we used indexing to access a specific element of array1. Notice the code,

Here,

array1[1,  ,  ,] - access the second 2D array, i.e.

[13, 14, 15, 16],
[17, 18, 19, 20],
[21, 22, 23, 24]

array1[  ,2,  ] - access the third row of the 2D array, i.e.

[21, 22, 23, 24]

array1[ , ,1] - access the second element of the third row, i.e.

[22]

In [3]:
#1D NumPy Array Slicing
# create a 1D array
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

# slice array1 from index 2 to index 6 (exclusive)
print(array1[2:6])  # [5 7 8 9]

# slice array1 from index 0 to index 8 (exclusive) with a step size of 2
print(array1[0:8:2])  # [1 5 8 2]

# slice array1 from index 3 up to the last element
print(array1[3:])  # [7 8 9 2 4 6]

# items from start to end
print(array1[:])   # [1 3 5 7 8 9 2 4 6]

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


In [ ]:
#In the above example, we have created the array named array1 with 9 elements.

#Then, we used the slicing operator : to slice array elements.

#array1[2:6] - slices array1 from index 2 to index 6, not including index 6
#array1[0:8:2] - slices array1 from index 0 to index 8, not including index 8
#array1[3:] - slices array1 from index 3 up to the last element
#array1[:] - returns all items from beginning to end

In [4]:
#Using start Parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
numbers[3:] = 20
print(numbers)

#Here, numbers[3:] = 20 replaces all the elements from index 3 onwards with new value 20.

[ 2  4  6 20 20 20]


In [5]:
#Using stop Parameter
import numpy as np

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify the first 3 elements
numbers[:3] = 40
print(numbers)

#Here, numbers[:3] = 20 replaces the first 3 elements with the new value 40.

[40 40 40  8 10 12]


In [7]:
#Using start and stop parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from indices 2 to 5
numbers[2:5] = 22
print(numbers)
#Here, numbers[2:5] = 22 selects elements from index 2 to index 4 and replaces them with new value 22.

[ 2  4 22 22 22 12]


In [9]:
#Using start, stop, and step parameter
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify every second element from indices 1 to 5
numbers[1:4:1] = 16
print(numbers)

#modifies every element from index 1 to index 4 with a new value 16.

[ 2 16 16 16 10 12]


In [10]:
#NumPy Array Negative Slicing
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# slice the last 3 elements of the array
# using the start parameter
print(numbers[-3:])    # [8 10 12]

# slice elements from 2nd-to-last to 4th-to-last element
# using the start and stop parameters
print(numbers[-5:-2])    # [4 6 8]

# slice every other element of the array from the end
# using the start, stop, and step parameters
print(numbers[-1::-2])   # [12 8 4]


#numbers[-3:] - slices last 3 elements of numbers
#numbers[-5:-2] - slices numbers elements from 5th last to 2nd last(excluded)
#numbers[-1::-2] - slices every other numbers elements from the end with step size 2

[ 8 10 12]
[4 6 8]
[12  8  4]


In [11]:
#Reverse NumPy Array Using Negative Slicing
# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# generate reversed array
reversed_numbers = numbers[::-1]
print(reversed_numbers)

#Here, the slice numbers[::-1] selects all the elements of the array with a step size of -1, which reverses the order of the elements.

[12 10  8  6  4  2]


In [13]:
#2D NumPy Array Slicing
#A 2D NumPy array can be thought of as a matrix, where each element has two indices, row index and column index.

#To slice a 2D NumPy array, we can use the same syntax as for slicing a 1D NumPy array.
#The only difference is that we need to specify a slice for each dimension of the array.
#array[row_start:row_stop:row_step, col_start:col_stop:col_step]
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                   [9, 11, 13, 15]])

print(array1[:2, :2])

#Here, the , in [:2, :2] separates the rows of the array.

#The first :2 returns first 2 rows i.e., entire array1. This results in

[[ 1  3]
 [ 9 11]]


Here, the , in [:2, :2] separates the rows of the array.

The first :2 returns first 2 rows i.e., entire array1. This results in
[1  3]

The second :2 returns first 2 columns from the 2 rows. This results in

[9 11]

In [15]:
#a 1D array.
np.array([1, 3, 5, 7, 2, 4, 6, 8])
#We can reshape this 1D array into N-d array as
# reshape 1D into 2D array
# with 2 rows and 4 columns
#[[1 3 5 7]
 #[2 4 6 8]]

# reshape 1D into 3D array
# with 2 rows, 2 columns, and 2 layers
#[[[1 3]
 # [5 7]]

 #[[2 4]
  #[6 8]]]


array([1, 3, 5, 7, 2, 4, 6, 8])

In [16]:
#Reshape 1D Array to 2D Array in NumPy
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array
# with 2 rows and 4 columns
result = np.reshape(array1, (2, 4))
print(result)

[[1 3 5 7]
 [2 4 6 8]]


In [19]:
# reshape a 1D array into a 2D array
# with 4 rows and 2 columns
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])
result1 = np.reshape(array1, (4, 2))
print("With 4 rows and 2 columns: \n",result1)


# reshape a 1D array into a 2D array with a single row
result2 = np.reshape(array1, (1, 8))
print("\nWith a single row: \n",result2)


#Note:

#We need to make sure that the new shape in reshape() has the same number of elements as the original array, else a ValueError will be raised.
#For example, reshaping an 8 element 1D array into a 2D array of 2 rows and 4 columns is possible,
##but reshaping it into a 2D array of 3 rows and 3 columns is not possible as that would require 3x3 = 9 elements.

With 4 rows and 2 columns: 
 [[1 3]
 [5 7]
 [2 4]
 [6 8]]

With a single row: 
 [[1 3 5 7 2 4 6 8]]


In [20]:
#Reshape 1D Array to 3D Array in NumPy
# create a 1D array
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape the 1D array to a 3D array
result = np.reshape(array1, (2, 2, 2))

# print the new array
print("1D to 3D Array: \n",result)


#Here, since there are 8 elements in the array1 array, np.reshape(array1, (2, 2, 2)) reshapes array1 into a 3D array with 2 rows, 2 columns and 2 layers.

1D to 3D Array: 
 [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


Flatten N-d Array to 1-D Array Using reshape()

Flattening an array simply means converting a multidimensional array into a 1D array.

To flatten an N-d array to a 1-D array we can use reshape() and pass "-1" as an argument.

In [22]:
# flatten 2D array to 1D
array1 = np.array([[1, 3], [5, 7], [9, 11]])
result1 = np.reshape(array1, -1)
print("Flattened 2D array:", result1)

# flatten 3D array to 1D
array2 = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
result2 = np.reshape(array2, -1)
print("Flattened 3D array:", result2)

#Here, reshape(array1, -1) and reshape(array2, -1) convert 2-D array and 3-D array into a 1-D array by collapsing all dimensions.

Flattened 2D array: [ 1  3  5  7  9 11]
Flattened 3D array: [1 3 5 7 2 4 6 8]
